extends: eslint:recommended
env:
  commonjs: true
  es6: true
  browser: true
rules:
  no-console: false
  no-magic-numbers:
    - warn
    - ignore:
      - 2   # geometry
      - 6
      - 30
      - 60
      - 100 # for percentage
      - 180
      - 1000