extends: userpixel/config/chrome-extension.js
env:
  commonjs: true
rules:
  no-magic-numbers:
    - warn
    - ignore:
      - 2   # geometry
      - 6
      - 30
      - 60
      - 100 # for percentage
      - 180
      - 1000